In [14]:
import numpy as np
from typing import Optional, Tuple

def agh_superfast_lu(a: np.matrix) -> Optional[Tuple[np.matrix, np.matrix]]:
    """Perform LU decomposition of a matrix.
    
    :param a: matrix
    :return:  (L, U)
    """
    n = a.shape[0]
    L = np.matrix(np.zeros(n*n).reshape(n, n))
    U = np.matrix(np.zeros(n*n).reshape(n, n))
    
    for i in range(n):
        L.itemset((i, i), 1)
        
    for k in range(n):
        for j in range(k, n):
            sum = a.item((k, j))
            for i in range(k):
                sum -= L.item((k, i)) * U.item(i, j)
            U.itemset((k, j), sum)
            
            sum = a.item((j, k))
            for i in range(k):
                sum -= L.item((j, i)) * U.item((i, k))
            sum /= U.item((k, k))
            L.itemset((j, k), sum)
    
    return (L, U)

a = np.matrix([[1,2,3],[1,0,2],[5,6,7]])

L, U = agh_superfast_lu(a)

print(L)
print(U)
print(L*U)

[[1. 0. 0.]
 [1. 1. 0.]
 [5. 2. 1.]]
[[ 1.  2.  3.]
 [ 0. -2. -1.]
 [ 0.  0. -6.]]
[[1. 2. 3.]
 [1. 0. 2.]
 [5. 6. 7.]]


In [17]:
def minor(arr,i,j) -> np.matrix:
    return arr[np.array(list(range(i))+list(range(i+1,arr.shape[0])))[:,np.newaxis],
               np.array(list(range(j))+list(range(j+1,arr.shape[1])))]

def agh_superfast_check_spd(a: np.matrix) -> bool:
    """Check whether a matrix is symmetric and positive-definite (SPD).
    
    :param a: matrix
    """
    n = a.shape[0]
    tmp = a
    for i in range(n-1, 0, -1):
        tmp = minor(tmp, i, i)
        if np.linalg.det(tmp) < 0:
            return false
    return np.all(a == a.transpose())

a = np.matrix([[2,-1,0],[-1,2,-1],[0,-1,2]])

b = np.matrix([[1,2],[3,4]])

print(agh_superfast_check_spd(a))
print(agh_superfast_check_spd(b))

True
False


In [44]:
import math

def agh_superfast_cholesky(a: np.matrix) -> Optional[np.matrix]:
    """Perform a Cholesky decomposition of a matrix.
    
    :param a: matrix
    :return:  matrix
    """
    
    n = a.shape[0]
    L = np.matrix(np.zeros(n*n).reshape(n,n))

    for k in range(n):
        tmp_sum = 0
        for j in range(k):
            tmp_sum += L.item((k,j)) * L.item((k,j))
        L.itemset((k, k), math.sqrt(a.item((k,k)) - tmp_sum))
    
        for i in range(k+1,n):
            tmp_sum = 0
            for j in range(k):
                tmp_sum += L.item((i,j)) * L.item((k,j))
            L.itemset((i,k), (1.0 / L.item((k,k)) * (a.item((i,k)) - tmp_sum)))
    return L

A = np.matrix([[6, 3, 4, 1], [3, 6, 0, 1], [4, 5, 10, 0], [0, 1, 7, 25]])
L = agh_superfast_cholesky(A)

print("A:")
print(A)

print("L:")
print(L)

A:
[[ 6  3  4  1]
 [ 3  6  0  1]
 [ 4  5 10  0]
 [ 0  1  7 25]]
L:
[[2.44948974 0.         0.         0.        ]
 [1.22474487 2.12132034 0.         0.        ]
 [1.63299316 1.41421356 2.30940108 0.        ]
 [0.         0.47140452 2.74241378 4.15414786]]
